Изменение первой буквы на заглавную
js-tasks-ru/jsbasic-20211108_dianakuzmina325 pull request #1
Opened 2021-10-31 13:16 UTC by divashka

2021-10-31 13:16 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2021-11-08 19:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-09 13:58 UTC, SinimaWath requested changes
Давай поправим задачи.

Перед тем как пушить задачу, вызывай `npm test`, чтобы проверить

2021-11-09 13:58 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  let n;
У тебя уже есть переменные m и n в аргументах функции. 

Поэтому у тебя ругаются тесты и браузер

SyntaxError: Identifier 'm' has already been declared

2021-11-09 13:58 UTC, SinimaWath commented on 0-module/1-task/index.js
> +alert(sum(2, 5));
Давай убирать информацию для тестирования из кода, они могут поломать тесты.

2021-11-09 13:58 UTC, SinimaWath commented on 1-module/3-task/index.js
> +alert(ucFirst('вася'));
Здесь тоже надо убрать alert

2021-11-11 12:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-11 12:54 UTC, SinimaWath approved these changes
Все ок

2021-11-11 12:55 UTC, merged