Занятие 6: JS классы и компоненты
js-tasks-ru/jsbasic-20211108_dianakuzmina325 pull request #9
Opened 2021-12-08 10:38 UTC by divashka

2021-12-08 10:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-09 06:13 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-09 13:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-12-09 20:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-10 18:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-11 20:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-12-13 09:59 UTC, SinimaWath requested changes

2021-12-13 09:59 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this.rows = rows;
Как ты видишь, у тебя получилось очень большая портянка кода из createElement и appendChild, поэтому такой метод обычно менее читаемый.

Давай переделаем на создание DOM елемента из Верстки:
- Можно сделать базовый елемент: `let table = document.createElement('table')`
- И в него записать всю верстку: `table.innerHTML = this.#getTemplate()`

2021-12-13 09:59 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    let carousel = createElement(`
Немного большой получается конструктор, попробуй его разбить еще, на логические функции:
```
let carousel = this.#createCarousel();

this.elem = this.#createCarousel();
```

2021-12-13 16:26 UTC, divashka commented on 6-module/3-task/index.js
> +    let carousel = createElement(`
Можно подробнее, не понимаю сути писать в переменную this.#createCarousel(); и потом ещё в свойство тоже самое

2021-12-13 21:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-15 10:33 UTC, SinimaWath approved these changes
все круто!

2021-12-15 10:33 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    let carousel = createElement(`
Тут я видимо ошибься, извиняюсь

2021-12-15 10:34 UTC, merged